* New upstream beta version.   + Catalog version number changed, older 9.4 clusters need to be dumped and     reloaded.   + Regexp regression fixed. (Closes: #760564)

diff --git a/debian/postgresql-9.4.preinst b/debian/postgresql-9.4.preinst
--- a/debian/postgresql-9.4.preinst
+++ b/debian/postgresql-9.4.preinst
@@ -1,11 +1,11 @@
 #!/bin/sh
 set -e
 
-# DB format changed between beta 1 and 2
+# DB format changed between beta 1 and 2 and 3
 if [ "$1" = "upgrade" -o "$1" = "install" ] && \
-    dpkg --compare-versions "$2" lt-nl "9.4~beta2"; then
+    dpkg --compare-versions "$2" lt-nl "9.4~beta3"; then
     if pg_lsclusters -h | grep -q '^9.4'; then
-        echo "ERROR: The database format changed between beta 1 and 2. Please dump your 9.4 clusters first and remove them before upgrading the package." >&2
+        echo "ERROR: The database format changed between beta 2 and 3. Please dump your 9.4 clusters first and remove them before upgrading the package." >&2
         exit 1
     fi
 fi
