Import 9.2 packaging.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,15 +1,21 @@
-#!/usr/bin/make	-f 
+#!/usr/bin/make -f
 TCL_VER := 8.5
 MAJOR_VER := 8.3
-DEB_TAR_SRCDIR:=postgresql-8.3.17
 
-include /usr/share/cdbs/1/rules/tarball.mk
-include /usr/share/cdbs/1/rules/simple-patchsys.mk
-include /usr/share/cdbs/1/class/autotools.mk
-include /usr/share/cdbs/1/rules/debhelper.mk
-
-LDFLAGS+= -Wl,--as-needed
+# support both hardening-wrapper (for backports) and dpkg-buildflags
+export DEB_BUILD_HARDENING = 1
+DPKG_EXPORT_BUILDFLAGS = 1
+-include /usr/share/dpkg/buildflags.mk
+export DEB_BUILD_MAINT_OPTIONS=hardening=-format
+export DEB_BUILD_HARDENING_FORMAT=0
+LDFLAGS+= -Wl,--as-needed -Wl,-z,now
 CFLAGS+= -fPIC
+
+# When protecting the postmaster with oom_adj=-17, allow the OOM killer to slay
+# the backends (http://archives.postgresql.org/pgsql-hackers/2010-01/msg00170.php)
+ifeq ($(shell uname -s),Linux)
+CFLAGS+= -DLINUX_OOM_ADJ=0
+endif
 
 ifneq ($(findstring $(DEB_BUILD_ARCH), sparc alpha),)
 # sparc and alpha's gcc currently miscompiles; see
@@ -17,112 +23,147 @@ ifneq ($(findstring $(DEB_BUILD_ARCH), sparc alpha),)
     CFLAGS+=-O1
 endif
 
-# do not yet enable hardening for Lenny, too close to release
-ifeq ($(shell lsb_release -is 2>/dev/null), Ubuntu)
-export DEB_BUILD_HARDENING=1
-endif
+export DPKG_GENSYMBOLS_CHECK_LEVEL=4
 
-# build should fail on test suite failures on all arches
-TESTSUITE_FAIL_CMD=exit 1
-
-DEB_DH_INSTALL_SOURCEDIR=debian/tmp
-DEB_CONFIGURE_EXTRA_FLAGS := --mandir=\$${prefix}/share/postgresql/$(MAJOR_VER)/man \
-  --with-docdir=\$${prefix}/share/doc/postgresql-doc-$(MAJOR_VER) \
+COMMON_CONFIGURE_FLAGS= \
+  --mandir=/usr/share/postgresql/$(MAJOR_VER)/man \
+  --with-docdir=/usr/share/doc/postgresql-doc-$(MAJOR_VER) \
   --sysconfdir=/etc/postgresql-common \
-  --datadir=\$${prefix}/share/postgresql/$(MAJOR_VER) \
-  --bindir=\$${prefix}/lib/postgresql/$(MAJOR_VER)/bin \
-  --includedir=\$${prefix}/include/postgresql/ \
+  --datadir=/usr/share/postgresql/$(MAJOR_VER) \
+  --bindir=/usr/lib/postgresql/$(MAJOR_VER)/bin \
+  --libdir=/usr/lib/ \
+  --libexecdir=/usr/lib/postgresql/ \
+  --includedir=/usr/include/postgresql/ \
   --enable-nls \
   --enable-integer-datetimes \
   --enable-thread-safety \
   --enable-debug \
   --disable-rpath \
-  --with-tcl \
-  --with-perl \
-  --with-python \
-  --with-pam \
-  --with-krb5 \
-  --with-gssapi \
-  --with-openssl \
-  --with-libxml \
-  --with-libxslt \
-  --with-ldap \
   --with-ossp-uuid \
   --with-gnu-ld \
-  --with-tclconfig=/usr/lib/tcl$(TCL_VER) \
-  --with-tkconfig=/usr/lib/tk$(TCL_VER) \
-  --with-includes=/usr/include/tcl$(TCL_VER) \
-  --with-system-tzdata=/usr/share/zoneinfo \
   --with-pgport=5432 \
-  $(ARCH_OPTS) \
+  --with-system-tzdata=/usr/share/zoneinfo \
   CFLAGS='$(CFLAGS)' \
   LDFLAGS='$(LDFLAGS)'
 
-DEB_DH_MAKESHLIBS_ARGS := -Xusr/lib/postgresql/$(MAJOR_VER)
-DEB_DH_INSTALLCHANGELOGS_ARGS := build-tree/postgresql-*/HISTORY
-DEB_COMPRESS_EXCLUDE := .source .c
-DEB_DH_INSTALLINIT_ARGS := -u'defaults 19 21'
+# build should fail on test suite failures on all arches
+TESTSUITE_FAIL_CMD=exit 1
 
-common-binary-predeb-arch::
-	# verify that all files are installed; ignore manpages, since
-	# they are handled by dh_installman
-	missing=`dh_install --sourcedir=debian/tmp --list-missing --no-act 2>&1 | grep -v man/man`; \
-	if [ -n "$$missing" ]; then \
-	    echo "Not all files are installed:"; \
-	    echo "$$missing"; \
-	    exit 1; \
+
+%:
+	dh $@
+
+override_dh_auto_configure: stamp/configure-build #stamp/configure-build-py3
+
+stamp/configure-build:
+	mkdir -p stamp build
+	cd build && ../configure \
+           --with-tcl \
+           --with-perl \
+           --with-python \
+           --with-pam \
+           --with-krb5 \
+           --with-gssapi \
+           --with-openssl \
+           --with-libxml \
+           --with-libxslt \
+           --with-ldap \
+           --with-tclconfig=/usr/lib/tcl$(TCL_VER) \
+           --with-tkconfig=/usr/lib/tk$(TCL_VER) \
+           --with-includes=/usr/include/tcl$(TCL_VER) \
+           PYTHON=/usr/bin/python \
+           $(COMMON_CONFIGURE_FLAGS)
+	touch "$@"
+	
+stamp/configure-build-py3:
+	mkdir build-py3
+	cd build-py3 && ../configure \
+           --with-python \
+           PYTHON=/usr/bin/python3 \
+           $(COMMON_CONFIGURE_FLAGS)
+	touch "$@"
+
+override_dh_auto_build: stamp/build #stamp/build-py3
+
+stamp/build: stamp/configure-build
+	cd build && $(MAKE)
+
+	# generate POT files for translators
+	find -name nls.mk -exec sh -c "make -C \$$(dirname {}) init-po" \;
+
+	# build tutorial stuff
+	make -C build/src/tutorial NO_PGXS=1
+
+	touch "$@"
+
+stamp/build-py3: stamp/configure-build-py3
+	cd build-py3 && $(MAKE)
+	touch "$@"
+
+override_dh_auto_install:
+	#make -C build-py3 install DESTDIR=$(CURDIR)/debian/tmp
+	make -C build install DESTDIR=$(CURDIR)/debian/tmp
+	# compress manpages
+	gzip -9n $(CURDIR)/debian/tmp/usr/share/postgresql/*/man/man*/*.[137]
+
+override_dh_makeshlibs:
+	dh_makeshlibs -Xusr/lib/postgresql/$(MAJOR_VER)
+
+override_dh_auto_clean:
+	rm -rf build* stamp
+
+override_dh_installchangelogs:
+	dh_installchangelogs HISTORY
+
+override_dh_compress:
+	dh_compress -X.source -X.c
+
+override_dh_install:
+	test ! -d debian/tmp/usr/local/pgsql/share/locale || mv debian/tmp/usr/local/pgsql/share/locale debian/tmp/usr/share
+	dh_install --fail-missing
+
+	# these get installed into the individual -/l* packages; -f because it
+	# does not exist for an -A build
+	rm -f debian/postgresql-contrib-$(MAJOR_VER)/usr/share/postgresql/$(MAJOR_VER)/extension/pl*
+
+	if [ -d debian/postgresql-doc-$(MAJOR_VER) ]; then \
+		install src/tutorial/*.c src/tutorial/*.source src/tutorial/Makefile src/tutorial/README debian/postgresql-doc-$(MAJOR_VER)/usr/share/doc/postgresql-doc-$(MAJOR_VER)/tutorial; \
 	fi
 
-common-post-build-arch::
-	# generate POT files for translators
-	find build-tree -name nls.mk -exec sh -c "make -C \$$(dirname {}) init-po" \;
-	
-common-post-build-indep::
-	# build tutorial stuff
-	make -C build-tree/$(DEB_TAR_SRCDIR)/src/tutorial NO_PGXS=1
-
-install/postgresql-doc-$(MAJOR_VER)::
-	install build-tree/$(DEB_TAR_SRCDIR)/src/tutorial/*.c build-tree/$(DEB_TAR_SRCDIR)/src/tutorial/*.source build-tree/$(DEB_TAR_SRCDIR)/src/tutorial/Makefile build-tree/$(DEB_TAR_SRCDIR)/src/tutorial/README debian/$(cdbs_curpkg)/usr/share/doc/$(cdbs_curpkg)/tutorial
-
-binary-predeb/postgresql-$(MAJOR_VER)::
+override_dh_auto_test:
 ifeq (, $(findstring nocheck, $(DEB_BUILD_OPTIONS)))
 	# patch away the "don't execute as root" check for the test
 	# suite; doing it here will ensure that the actual debs have
 	# the check.
-	set -e; cd build-tree/$(DEB_TAR_SRCDIR); \
-	patch --no-backup-if-mismatch -p1 < ../../debian/disable-root-check.patch; \
-	make -C src/test/regress bigcheck || fail=1; \
-	patch --no-backup-if-mismatch -Rp1 < ../../debian/disable-root-check.patch; \
+	set -e; \
+	patch --no-backup-if-mismatch -p1 < debian/disable-root-check.patch; \
+	patch --no-backup-if-mismatch -p1 < debian/pg_regress-in-tmp.patch; \
+	make -C build/src/test/regress bigcheck || fail=1; \
+	patch --no-backup-if-mismatch -Rp1 < debian/pg_regress-in-tmp.patch; \
+	patch --no-backup-if-mismatch -Rp1 < debian/disable-root-check.patch; \
 	if [ -n "$$fail" ]; then \
 	    for l in regression.diffs log/initdb.log log/postmaster.log; do \
-	    	if [ -e src/test/regress/$$l ]; then \
+	    	if [ -e build/src/test/regress/$$l ]; then \
 		    echo "********* $$l *******"; \
-		    cat src/test/regress/$$l; \
+		    cat build/src/test/regress/$$l; \
 		fi; \
 	    done; \
 	    $(TESTSUITE_FAIL_CMD); \
 	fi
 endif
 
-	# compress manpages
-	find debian/postgresql-$(MAJOR_VER)/usr/share/postgresql/$(MAJOR_VER)/man -type f -exec gzip -9 '{}' \;
-
-binary-predeb/postgresql-client-$(MAJOR_VER)::
-	find debian/postgresql-client-$(MAJOR_VER)/usr/share/postgresql/$(MAJOR_VER)/man -type f -exec gzip -9 '{}' \;
-
-binary-install/postgresql-plpython-$(MAJOR_VER)::
-	dh_pycentral -p$(cdbs_curpkg)
-	dh_python -p$(cdbs_curpkg) usr/lib/postgresql/$(MAJOR_VER)/lib
+override_dh_strip:
+	dh_strip --dbg-package=postgresql-$(MAJOR_VER)-dbg
 
 # run tests in contrib in temporary test installations, using programs
-# from build-tree
+# from local tree
 contrib-check:
-	set -e; cd build-tree/$(DEB_TAR_SRCDIR)/contrib; \
+	set -e; cd build/contrib; \
 	for d in *; do \
 	    [ -d $$d/sql ] || continue; \
 	    echo "==============  Running tests in $$d"; \
 	    (cd $$d; \
-	    if ! ../../src/test/regress/pg_regress --top-builddir=../.. --temp-install=$(CURDIR)/build-tree/tmp_check --dbname=contrib_regression `cd sql; ls *.sql | sed 's/.sql$$//'`; then \
+	    if ! ../../src/test/regress/pg_regress --top-builddir=../.. --temp-install=tmp_check --dbname=contrib_regression `cd sql; ls *.sql | sed 's/.sql$$//'`; then \
 		 cat regression.diffs; \
 	    fi); \
 	done
@@ -131,16 +172,16 @@ contrib-check:
 # from system installation
 contrib-installcheck:
 	# set up temporary db
-	rm -rf build-tree/tmp_data
-	mkdir build-tree/tmp_data
-	/usr/lib/postgresql/$(MAJOR_VER)/bin/initdb -D build-tree/tmp_data
-	/usr/lib/postgresql/$(MAJOR_VER)/bin/pg_ctl -D build-tree/tmp_data -l build-tree/tmp_data/postgres.log -o '-k /tmp' start
+	rm -rf tmp_data
+	mkdir tmp_data
+	/usr/lib/postgresql/$(MAJOR_VER)/bin/initdb -D tmp_data
+	/usr/lib/postgresql/$(MAJOR_VER)/bin/pg_ctl -D tmp_data -l tmp_data/postgres.log -o '-k /tmp' start
 	# wait until it started up
 	while !/usr/lib/postgresql/$(MAJOR_VER)/bin/psql -h /tmp -l >/dev/null 2>&1; do sleep 1; done
 	sleep 1
 	while !/usr/lib/postgresql/$(MAJOR_VER)/bin/psql -h /tmp -l >/dev/null 2>&1; do sleep 1; done
 	# run the tests
-	-cd build-tree/$(DEB_TAR_SRCDIR)/contrib; make installcheck
-	/usr/lib/postgresql/$(MAJOR_VER)/bin/pg_ctl -D build-tree/tmp_data stop
+	-cd build/contrib; make installcheck
+	/usr/lib/postgresql/$(MAJOR_VER)/bin/pg_ctl -D tmp_data stop
 	# find and print the regression diffs
-	find build-tree/$(DEB_TAR_SRCDIR)/contrib/ -name regression.diffs -exec cat '{}' \;
+	find build/contrib/ -name regression.diffs -exec cat '{}' \;
